url: "https://Grentchello.github.io"
baseurl: "/Blog3"
repository: "Grentchello/Blog3"
title: My Reading and Movie Blog
author: Charlotte
description: A place to document my reads

theme: minima

